import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../component/layout'

export default function Home() { 

  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Konnex IoT Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">konnex</a>
        </h1>

        <p className={styles.description}>
          Get started to Create OPCUA Connection
        </p>

        <div className={styles.grid}>
          <a href="/opcua-server" className={styles.card}>
            <h2>Create Server &rarr;</h2>
            <p>Create OPC UA Server, Connect your IoT Device</p>
          </a>

          <a href="/opcua-client" className={styles.card}>
            <h2>Create Client &rarr;</h2>
            <p>Create OPC UA Client, Monitor your IoT Data</p>
          </a>

          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
    </Layout>
  )
}
